#Ubuntu: `apr-config --includedir`
INCLUDE_DIR="/usr/include/apr-1.0"

all: htntlm htx2b

static: htntlm_static htx2b_static
debug: htntlm_debug htx2b_debug

htntlm_static: htntlm.c
	cc ${CFLAGS} -Wall -O2 -static -DLINUX=2 -D_REENTRANT -D_GNU_SOURCE -I${INCLUDE_DIR} htntlm.c -o htntlm -lapr-1 -luuid -lrt -lcrypt -lpthread -ldl -lpcre -lssl -lcrypto -lz -ldl

htx2b_static: htx2b.c
	cc ${CFLAGS} -Wall -O2 -static -DLINUX=2 -D_REENTRANT -D_GNU_SOURCE -I${INCLUDE_DIR} htx2b.c -o htx2b -lapr-1 -luuid -lrt -lcrypt -lpthread -lcrypto -lz -ldl

htntlm_debug: htntlm.c
	cc ${CFLAGS} -Wall -g -DLINUX=2 -D_REENTRANT -D_GNU_SOURCE -I. -I../3thrdparty/apr/include -I../3thrdparty/apr-util/include -I../3thrdparty/openssl/include -c htntlm.c -o htntlm.o
	cc ${CFLAGS} -o htntlm htntlm.o ../3thrdparty/pcre/.libs/libpcre.a ../3thrdparty/apr-util/.libs/libaprutil-1.a ../3thrdparty/apr/.libs/libapr-1.a -lpthread ../3thrdparty/openssl/libssl.a ../3thrdparty/openssl/libcrypto.a -ldl
htx2b_debug: htx2b.c
	cc ${CFLAGS} -Wall -g -DLINUX=2 -D_REENTRANT -D_GNU_SOURCE -I. -I../3thrdparty/apr/include -I../3thrdparty/apr-util/include -c htx2b.c -o htx2b.o
	cc ${CFLAGS} -o htx2b htx2b.o ../3thrdparty/apr-util/.libs/libaprutil-1.a ../3thrdparty/apr/.libs/libapr-1.a -ldl -pthread

htntlm: htntlm.c
	cc ${CFLAGS} -Wall -O2 -DLINUX=2 -D_REENTRANT -D_GNU_SOURCE -I. -I${INCLUDE_DIR} -c htntlm.c -o htntlm.o
	cc ${CFLAGS} -o htntlm htntlm.o  -lapr-1 -laprutil-1 -luuid -lrt -lcrypt -lpthread -ldl -lpcre -lssl

htx2b: htx2b.c
	cc ${CFLAGS} -Wall -O2 -DLINUX=2 -D_REENTRANT -D_GNU_SOURCE -I. -I${INCLUDE_DIR} -c htx2b.c -o htx2b.o
	cc ${CFLAGS} -o htx2b htx2b.o  -lapr-1 -luuid -lrt -lcrypt -lpthread -ldl

install:
	cp htntlm /usr/bin
	cp htx2b /usr/bin

clean:
	rm -f htntlm htx2b *.o *~

test:
	./run_all_test.sh ../test/*.txt
